repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v2.3.0
        hooks:
        # -   id: check-yaml
        -   id: end-of-file-fixer
        -   id: trailing-whitespace

    - repo: https://github.com/humitos/mirrors-autoflake.git
      rev: v1.3
      hooks:
        - id: autoflake
          args: ['--in-place', '--expand-star-imports', '--ignore-init-module-imports', '--remove-all-unused-imports']

    -   repo: https://github.com/timothycrosley/isort
        rev: 5.5.1
        hooks:
        -  id: isort

    -   repo: https://github.com/psf/black
        rev: 20.8b1
        hooks:
        -   id: black
            args: [--line-length=100]
