AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template to create EC2 instance.'

Parameters:
  # Update these parameters
  SubnetId:
    Default: subnet-123
    Type: String
  LustreBucketName:
    Default: dlmodels
    Type: String

  # These parameters can be kept
  AvailabilityZone:
    Default: us-east-1b # No p3dn's in 1a
    Type: String
  StorageCapacity:
    Default: 3600 # In GiB, must be a multiple of 1200
    Type: Number
  InstanceName:
    Default: albert-fsx
    Type: String

Resources:
  FileSystem:
    Type: AWS::FSx::FileSystem
    Properties:
      FileSystemType: LUSTRE
      LustreConfiguration:
        ImportPath: !Join ["", ["s3://", !Ref LustreBucketName, "/fsx-import"]]
        ExportPath: !Join ["", ["s3://", !Ref LustreBucketName, "/fsx-export"]]
      StorageCapacity: !Ref StorageCapacity
      SubnetIds:
        - !Ref SubnetId
      Tags:
        - Key: Name
          Value: !Ref InstanceName

Outputs:
  FileSystemId:
    Description: The Lustre FSx id
    Value: !Ref FileSystem
