AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template to create EC2 instance.'

Parameters:
  # Update these parameters
  SubnetId:
    Default: subnet-123
    Type: String
  LustreBucketName:
    Default: dlmodels
    Type: String

  # These parameters can be kept
  AvailabilityZone:
    Default: us-east-1b # No p3dn's in 1a
    Type: String
  StorageCapacity:
    Default: 9600 # In GiB, must be a multiple of 2400
    Type: Number
  InstanceName:
    Default: dlmodels-fsx-2
    Type: String

Resources:
  FileSystem:
    Type: AWS::FSx::FileSystem
    Properties:
      FileSystemType: LUSTRE
      StorageCapacity: !Ref StorageCapacity
      LustreConfiguration:
        DeploymentType: SCRATCH_2
      SubnetIds:
        - !Ref SubnetId
      Tags:
        - Key: Name
          Value: !Ref InstanceName

Outputs:
  FileSystemId:
    Description: The Lustre FSx id
    Value: !Ref FileSystem
